apiVersion: v1
kind: Secret
metadata:
  name: confluent-api-secret
  namespace: monitoring
type: Opaque
stringData:
  BASIC_AUTH_USERNAME: "2HNY7JSYJVCWAZET"
  BASIC_AUTH_PASSWORD: "cfltmA0leu0ONf9ZPLD8q0Jh72JfM4PA5QWPKSmyE2mXmVnCRy59Pw4xq+MqiSEw"
