apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-access-sa
  namespace: redpanda-migrator
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::723817280415:role/S3-access-redpanda-config
